name: Build Docs and Send Metrics

on:
  push:
    branches: [ develop, main ]
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install sphinx || true

      - name: Run DocMonitor Lite Agent
        env:
          DOCMONITOR_URL: "https://irradiatingly-unsoothed-adah.ngrok-free.dev"  # или твой внешний API
        run: |
          chmod +x .github/docmonitor/dmci-lite.sh
          .github/docmonitor/dmci-lite.sh
