---
# Процесс сборки тестовой версии сайта и выгрузки его на хостинг по FTP
name: Build testing site and deploy to FTP

# Запуск workflow при обновлении ветки develop
on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy-prod:
    runs-on: ubuntu-latest

    steps:
      # Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Обновление списка доступных пакетов
      - name: Update APT index
        run: sudo apt-get update

      # Установка пакетов, необходимых для сборки сайта
      - name: Install make, graphviz and JRE
        run: sudo apt-get install make graphviz default-jre --yes --no-install-recommends

      # Установка актуальной версии Python
      - name: Install Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Обновление PIP и установка Python-модулей, указанных в файле requirements.txt
      - name: Update PIP and install requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      # Сборка проекта в формате html
      - name: Buils Sphinx project
        run: make html

      # Отправка метрик этой сборки в  DocMonitor
      - name: Send build metrics to DocMonitor
        if: always()
        env:
          DOCMONITOR_URL: "https://irradiatingly-unsoothed-adah.ngrok-free.dev"
          DOCMONITOR_PROJECT: "web3"
          DOCMONITOR_BRANCH: ${{ github.ref_name }}
          DOCMONITOR_COMMIT: ${{ github.sha }}
        run: |
          chmod +x .github/docmonitor/dmci-lite.sh
          .github/docmonitor/dmci-lite.sh "noop"

      # ====== ВЫГРУЗКА НА FTP ВРЕМЕННО ОТКЛЮЧЕНА ======
      # - name: Upload to FTP
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.0
      #   with:
      #     server: ${{ secrets.FTP_HOST }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     server-dir: web3.techwriters.ru/
      #     local-dir: build/html/
